class Player {
  int id;
  int gameScheduleId;
  int userId;
  String memberType;
  Null userNamePostFix;
  String status;
  String createdAt;
  String updatedAt;
  String serverLink;
  int hasDisability;
  String gamerAlias;
  String name;
  String email;
  Null emailVerifiedAt;
  String password;
  Null rememberToken;
  String lastName;
  String registeredUser;
  String ssoUserLogin;
  String ssoUserNicename;
  String ssoUserUserRegistered;
  int ssoUserUserStatus;
  String ssoUserDisplayName;
  String ssoUserFirstName;
  String ssoUserLastName;
  String ssoUserFbToken;
  Null mood;
  String chatStatus;
  Null webPnToken;
  String androidPnToken;
  String primaryAddressStreet;
  String primaryAddressCity;
  String primaryAddressState;
  String primaryAddressCountry;
  String primaryAddressPostalcode;
  String timeZone;
  String theme;
  String ipCity;
  String ipContinent;
  String ipCountry;
  String ipLocation;
  String ipTimezone;
  String ipZip;
  String ipState;
  String ipIsp;
  String ipOrg;
  String ipAddress;
  String ua;
  String browser;
  String os;
  String device;
  int playerId;
  int talkAttempts;
  double talkTime;
  int statId;
  int memberId;
  String interactions;
  String uniqueInteractions;
  String chat;

  Player({this.id, this.gameScheduleId, this.userId, this.memberType, this.userNamePostFix, this.status, this.createdAt, this.updatedAt, this.serverLink, this.hasDisability, this.gamerAlias, this.name, this.email, this.emailVerifiedAt, this.password, this.rememberToken, this.lastName, this.registeredUser, this.ssoUserLogin, this.ssoUserNicename, this.ssoUserUserRegistered, this.ssoUserUserStatus, this.ssoUserDisplayName, this.ssoUserFirstName, this.ssoUserLastName, this.ssoUserFbToken, this.mood, this.chatStatus, this.webPnToken, this.androidPnToken, this.primaryAddressStreet, this.primaryAddressCity, this.primaryAddressState, this.primaryAddressCountry, this.primaryAddressPostalcode, this.timeZone, this.theme, this.ipCity, this.ipContinent, this.ipCountry, this.ipLocation, this.ipTimezone, this.ipZip, this.ipState, this.ipIsp, this.ipOrg, this.ipAddress, this.ua, this.browser, this.os, this.device, this.playerId, this.talkAttempts, this.talkTime, this.statId, this.memberId, this.interactions, this.uniqueInteractions, this.chat});

  Player.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    gameScheduleId = json['gameScheduleId'];
    userId = json['userId'];
    memberType = json['memberType'];
    userNamePostFix = json['userNamePostFix'];
    status = json['status'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    serverLink = json['serverLink'];
    hasDisability = json['hasDisability'];
    gamerAlias = json['gamerAlias'];
    name = json['name'];
    email = json['email'];
    emailVerifiedAt = json['email_verified_at'];
    password = json['password'];
    rememberToken = json['remember_token'];
    lastName = json['lastName'];
    registeredUser = json['registeredUser'];
    ssoUserLogin = json['sso_user_login'];
    ssoUserNicename = json['sso_user_nicename'];
    ssoUserUserRegistered = json['sso_user_user_registered'];
    ssoUserUserStatus = json['sso_user_user_status'];
    ssoUserDisplayName = json['sso_user_display_name'];
    ssoUserFirstName = json['sso_user_first_name'];
    ssoUserLastName = json['sso_user_last_name'];
    ssoUserFbToken = json['sso_user_fb_token'];
    mood = json['mood'];
    chatStatus = json['chat_status'];
    webPnToken = json['web_pn_token'];
    androidPnToken = json['android_pn_token'];
    primaryAddressStreet = json['primary_address_street'];
    primaryAddressCity = json['primary_address_city'];
    primaryAddressState = json['primary_address_state'];
    primaryAddressCountry = json['primary_address_country'];
    primaryAddressPostalcode = json['primary_address_postalcode'];
    timeZone = json['time_zone'];
    theme = json['theme'];
    ipCity = json['ip_city'];
    ipContinent = json['ip_continent'];
    ipCountry = json['ip_country'];
    ipLocation = json['ip_location'];
    ipTimezone = json['ip_timezone'];
    ipZip = json['ip_zip'];
    ipState = json['ip_state'];
    ipIsp = json['ip_isp'];
    ipOrg = json['ip_org'];
    ipAddress = json['ipAddress'];
    ua = json['ua'];
    browser = json['browser'];
    os = json['os'];
    device = json['device'];
    playerId = json['playerId'];
    talkAttempts = json['TalkAttempts'];
    talkTime = json['TalkTime'];
    statId = json['statId'];
    memberId = json['memberId'];
    interactions = json['interactions'];
    uniqueInteractions = json['uniqueInteractions'];
    chat = json['chat'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['gameScheduleId'] = this.gameScheduleId;
    data['userId'] = this.userId;
    data['memberType'] = this.memberType;
    data['userNamePostFix'] = this.userNamePostFix;
    data['status'] = this.status;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['serverLink'] = this.serverLink;
    data['hasDisability'] = this.hasDisability;
    data['gamerAlias'] = this.gamerAlias;
    data['name'] = this.name;
    data['email'] = this.email;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['password'] = this.password;
    data['remember_token'] = this.rememberToken;
    data['lastName'] = this.lastName;
    data['registeredUser'] = this.registeredUser;
    data['sso_user_login'] = this.ssoUserLogin;
    data['sso_user_nicename'] = this.ssoUserNicename;
    data['sso_user_user_registered'] = this.ssoUserUserRegistered;
    data['sso_user_user_status'] = this.ssoUserUserStatus;
    data['sso_user_display_name'] = this.ssoUserDisplayName;
    data['sso_user_first_name'] = this.ssoUserFirstName;
    data['sso_user_last_name'] = this.ssoUserLastName;
    data['sso_user_fb_token'] = this.ssoUserFbToken;
    data['mood'] = this.mood;
    data['chat_status'] = this.chatStatus;
    data['web_pn_token'] = this.webPnToken;
    data['android_pn_token'] = this.androidPnToken;
    data['primary_address_street'] = this.primaryAddressStreet;
    data['primary_address_city'] = this.primaryAddressCity;
    data['primary_address_state'] = this.primaryAddressState;
    data['primary_address_country'] = this.primaryAddressCountry;
    data['primary_address_postalcode'] = this.primaryAddressPostalcode;
    data['time_zone'] = this.timeZone;
    data['theme'] = this.theme;
    data['ip_city'] = this.ipCity;
    data['ip_continent'] = this.ipContinent;
    data['ip_country'] = this.ipCountry;
    data['ip_location'] = this.ipLocation;
    data['ip_timezone'] = this.ipTimezone;
    data['ip_zip'] = this.ipZip;
    data['ip_state'] = this.ipState;
    data['ip_isp'] = this.ipIsp;
    data['ip_org'] = this.ipOrg;
    data['ipAddress'] = this.ipAddress;
    data['ua'] = this.ua;
    data['browser'] = this.browser;
    data['os'] = this.os;
    data['device'] = this.device;
    data['playerId'] = this.playerId;
    data['TalkAttempts'] = this.talkAttempts;
    data['TalkTime'] = this.talkTime;
    data['statId'] = this.statId;
    data['memberId'] = this.memberId;
    data['interactions'] = this.interactions;
    data['uniqueInteractions'] = this.uniqueInteractions;
    data['chat'] = this.chat;
    return data;
  }
}